version: 2.1
orbs:
  node: circleci/node@5
  win: circleci/windows@4.1.1
#   # heroku: circleci/heroku@1.2.6

jobs:
  test:
    executor:
      name: win/default # executor type
      size: medium

    steps:
      - checkout
      - run: echo "test application"
      - run: npm install
      - run: npm run test

  coverage:
    executor:
      name: win/default # executor type
      size: medium

    steps:
      - checkout
      - run: echo "test coverage"
      - run: npm install
      # - run: npm run coverage
workflows:
  version: 2.1
  test_coverage:
    jobs:
      - test
      - coverage
# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
# version: 2.1

# # Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.3.1

# # Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
# workflows:
#   # Name the workflow "Welcome"
#   Welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run

# build:
#   docker:
#     - image: circleci/node:19
#   steps:
#     - checkout
#     - run: echo "npm running build"
#     - run: npm install
#     - run: CI=true npm run build
# executor: node/default
# - node/install-packages:
#     install-npm: true
#     node-version: '19.0'
#     steps:
#       - checkout
#           pkg-manager: npm
#       - run:
#           command: npm test
#           name: Run tests
#       - run:
#           command: npm build
#           name: Build app
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .
